/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_tridiumap_niagaraDll_DllLoader */

#ifndef _Included_com_tridiumap_niagaraDll_DllLoader
#define _Included_com_tridiumap_niagaraDll_DllLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tridiumap_niagaraDll_DllLoader
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tridiumap_niagaraDll_DllLoader_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
